# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GitTestProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GitTestProject
  
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'SwiftKeychainWrapper'

  target 'GitTestProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GitTestProjectUITests' do
    # Pods for testing
  end

end
